= ocp4-workload-quarkus-workshop - Deploy Quarkus Workshop into OCP4

== Role overview

* This role deploys logging into an OpenShift 4 Cluster. It depends on infrastructure nodes existing. It consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment.
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to deploy logging
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to
 delete the workload
*** This role removes the logging deployment and project but not the operator configs
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* The variable *ocp_username* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line

== Deploy Workload at an existing OpenShift Cluster 4x:

[source,shell]
----
$ oc login ...
$ sh run-local.sh
----

== TODO

 Remember to have the URL's used, eg: in your `/etc/hosts` file

[source,shell]
----
# Quarkus Workshop
YOUR.IP keycloak-rhsso-rfelix.apps.myopenshift.com
YOUR.IP codeready-codeready-rfelix.apps.myopenshift.com
YOUR.IP web-m1-guides-rfelix.apps.myopenshift.com
YOUR.IP web-m2-guides-rfelix.apps.myopenshift.com
YOUR.IP web-m3-guides-rfelix.apps.myopenshift.com
YOUR.IP keycloak-codeready-rfelix.apps.myopenshift.com
YOUR.IP plugin-registry-codeready-rfelix.apps.myopenshift.com
YOUR.IP devfile-registry-codeready-rfelix.apps.myopenshift.com
YOUR.IP get-a-username-guides-rfelix.apps.myopenshift.com
----
