---
# Setup AMQ Streams (kafka) via operator
- name: Create OpenShift Objects for amq streams
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./templates/amqstreams_subscription.yaml.j2

# wait for amq (kafka) CRDs
- name: Wait for Kafka CRD
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: kafkas.kafka.strimzi.io
  register: r_kafka_crd
  retries: 200
  delay: 10
  until: r_kafka_crd.resources | list | length == 1


