---
- name: create project for {{ t_user }}
  kubernetes.core.k8s:
    state: present
    kind: Namespace
    name: "{{ t_project_name }}"
    definition:
      metadata:
        annotations:
          openshift.io/description: ""
          openshift.io/display-name: "{{ workshop_openshift_namespace_user_x_display_name }} {{ t_user }}"
        labels:
          workshop: "{{ workshop_openshift_namespace_label }}"

- name: assign permissions for user {{ t_user }}
  kubernetes.core.k8s:
    state: present
    kind: RoleBinding
    api_version: rbac.authorization.k8s.io/v1
    definition:
      metadata:
        name: admin
        namespace: "{{ t_project_name }}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin
      subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: "{{ t_user }}"
