#---
#- name: Verify everything is deployed correctly
#  include_tasks: verify-workload.yaml
#
## Implement your Post Workload deployment tasks here
#- name: lab data for user info
#  agnosticd_user_info:
#    user: "{{ item }}"
#    msg: |
#      Username: {{ item }}
#      {% for m in modules %}
#      Workshop User Guide: http://web-{{ m }}-{{ workshop_openshift_namespace_guide }}.{{ route_subdomain }}
#      {% endfor %}
#  loop: "{{ users }}"
#
#- name: output workshop info
#  agnosticd_user_info:
#    msg: |
#      RHSSO Workshop provisioned for {{ num_users }} user(s)
#
#      URL for attendees to get a username assigned to them and links to labs:
#
#      https://get-a-username-{{ workshop_openshift_namespace_guide }}.{{ route_subdomain }}
#
#      You should share this URL (or a shortlink for it) -- It is all they will need to get started!
#
#      [Instructor Only] To access the admin see which user is assigned to which user ID, use the following:
#
#      [Instructor Only] https://get-a-username-{{ workshop_openshift_namespace_guide }}.{{ route_subdomain }}/admin
#
#      [Instructor Only] Admin login with 'admin' / '{{ workshop_openshift_user_password }}'
#
#- name: output workshop username distribution URL
#  agnosticd_user_info:
#    msg: |
#      Individual module guide URLs (in case you need them for direct linking):
#
#- name: output workshop info guides
#  agnosticd_user_info:
#    msg: |
#      Module 1 http://web-m1-{{ workshop_openshift_namespace_guide }}.{{ route_subdomain }}
#  when: ("m1" in modules)
#
#- name: output workshop info guides
#  agnosticd_user_info:
#    msg: |
#      Module 2 http://web-m2-{{ workshop_openshift_namespace_guide }}.{{ route_subdomain }}
#  when: ("m2" in modules)
#
#- name: output workshop info guides
#  agnosticd_user_info:
#    msg: |
#      Module 3 http://web-m3-{{ workshop_openshift_namespace_guide }}.{{ route_subdomain }}
#  when: ("m3" in modules)
#
#- name: output workshop info guides
#  agnosticd_user_info:
#    msg: |
#      OpenShift credentials for attendees: {{ workshop_openshift_user_name }} / {{ workshop_openshift_user_password }}
#
#      OpenShift/Kubernetes API (use with oc login): {{ master_url }}
#
#      Red Hat SSO Console: https://secure-rhsso-{{ workshop_openshift_namespace_rhsso }}.{{ route_subdomain }}
#      Admin login with '{{workshop_rhsso_admin_user_name}}' / '{{workshop_rhsso_admin_password}}'
#  when: not silent|bool
#
## Leave this as the last task in the playbook.
#- name: post_workload tasks complete
#  agnosticd_user_info:
#    msg: |
#      Post-Workload Tasks completed successfully.
#  when: not silent|bool
